apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.secret }}
  labels:
    {{- include "airqo-docs-website.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store   # switched to Azure Key Vault store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.secret }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.app.secret }} # key in GCP Secret Manager
        version: latest
