apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.secret }}
  labels:
    {{- include "airqo-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager   # your existing ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.secret }}
    creationPolicy: Owner
  data:
    - secretKey: .env       # key in the Kubernetes secret
      remoteRef:
        key: {{ .Values.app.secret }} # key in GCP Secret Manager
        version: latest
