# values for platform frontend.
env:
  deployment_name: airqo-dev-platform-frontend
  service_name: airqo-dev-platform-ui-svc
  labels: dev-platform-ui
  secret: env-development

replicaCount: 2

image:
  repository: airqo-dev-platform-frontend
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  nodePort: 32104
  targetPort: 80
  port: 80

ingress:
  enabled: false

nodeSelector: {}
resources: {}
affinity: {}
torelations: {}


## Application level settings  
appMode: development