name: run-tests

on:
  pull_request:
    branches:
      - staging

jobs:
  check:
    name: check for changed frontends
    outputs:
      run_next_platform: ${{ steps.check_files.outputs.run_next_platform }} # next platform

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified frontends
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt

          echo "::set-output name=run_next_platform::false"  

          while IFS= read -r file
          do
            if [[ $file == platform/* ]]; then
              echo "::set-output name=run_next_platform::true"
            fi

          done < files.txt

  ### next-platform changes ###
  next-platform:
    name: test-next-platform
    needs: [check]
    if: needs.check.outputs.run_next_platform == 'true'
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.0-chrome99-ff97
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google login
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_CREDENTIALS }}

      - name: Setup Cloud SDK(gcloud)
        uses: google-github-actions/setup-gcloud@v0

      - name: Create .env file
        run: |
          gcloud secrets versions access latest --secret="sta-env-next-platform" > platform/.env
          echo "INSTRUMENT_CODE=1" >> platform/.env

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./platform/
          build: yarn build
          start: yarn start
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: code-coverage

      - name: Deploy code coverage report ðŸš€
        uses: codecov/codecov-action@v3
        with:
          directory: ./platform/coverage/lcov-report
